# Generated by Django 2.0.2 on 2018-03-10 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsonmodel',
            old_name='Barometer_Altitude',
            new_name='barometer_Altitude',
        ),
        migrations.RenameField(
            model_name='jsonmodel',
            old_name='Barometer_Pressure',
            new_name='barometer_Pressure',
        ),
        migrations.RenameField(
            model_name='jsonmodel',
            old_name='Barometer_Temperature',
            new_name='barometer_temperature',
        ),
        migrations.RenameField(
            model_name='jsonmodel',
            old_name='GAS_H2',
            new_name='gas_h2',
        ),
        migrations.RenameField(
            model_name='jsonmodel',
            old_name='Gas_NH3',
            new_name='gas_nh3',
        ),
        migrations.RenameField(
            model_name='jsonmodel',
            old_name='Gas_NO2',
            new_name='gas_no2',
        ),
        migrations.RenameField(
            model_name='jsonmodel',
            old_name='Humidity_SHT11',
            new_name='humidity_sht11',
        ),
        migrations.RenameField(
            model_name='jsonmodel',
            old_name='IMU_Ax',
            new_name='imu_ax',
        ),
        migrations.RenameField(
            model_name='jsonmodel',
            old_name='IMU_Ay',
            new_name='imu_ay',
        ),
        migrations.RenameField(
            model_name='jsonmodel',
            old_name='IMU_Az',
            new_name='imu_az',
        ),
        migrations.RenameField(
            model_name='jsonmodel',
            old_name='IMU_Cx',
            new_name='imu_cx',
        ),
        migrations.RenameField(
            model_name='jsonmodel',
            old_name='IMU_Cy',
            new_name='imu_cy',
        ),
        migrations.RenameField(
            model_name='jsonmodel',
            old_name='IMU_Cz',
            new_name='imu_cz',
        ),
        migrations.RenameField(
            model_name='jsonmodel',
            old_name='IMU_Gx',
            new_name='imu_gx',
        ),
        migrations.RenameField(
            model_name='jsonmodel',
            old_name='IMU_Gy',
            new_name='imu_gy',
        ),
        migrations.RenameField(
            model_name='jsonmodel',
            old_name='IMU_Gz',
            new_name='imu_gz',
        ),
        migrations.RenameField(
            model_name='jsonmodel',
            old_name='Promedio_temperatura',
            new_name='mean_temperature',
        ),
        migrations.RenameField(
            model_name='jsonmodel',
            old_name='Temperature_SHT11',
            new_name='temperature_sht11',
        ),
        migrations.RenameField(
            model_name='jsonmodel',
            old_name='Time_Milisenconds',
            new_name='time_milisenconds',
        ),
    ]
