# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-17 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple3', '0003_auto_20180310_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonmodel',
            name='voltaje_bateria',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
