# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-04 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple3', '0004_jsonmodel_voltaje_bateria'),
    ]

    operations = [
        migrations.CreateModel(
            name='TramaCorta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_time', models.CharField(max_length=50, null=True)),
                ('gps_latitude', models.CharField(max_length=50, null=True)),
                ('gps_longitude', models.CharField(max_length=50, null=True)),
                ('gps_altitude', models.CharField(max_length=50, null=True)),
                ('gps_course', models.CharField(max_length=50, null=True)),
                ('gps_speed', models.CharField(max_length=50, null=True)),
                ('barometer_Pressure', models.CharField(max_length=50, null=True)),
                ('barometer_Altitude', models.CharField(max_length=50, null=True)),
                ('temperature_sht11', models.CharField(max_length=50, null=True)),
                ('voltaje_bateria', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
