# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-27 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple3', '0007_imagenes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=30000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='img',
            field=models.CharField(max_length=30000, null=True),
        ),
    ]
